package vn.viettechtrans.app.speech

import android.content.res.AssetManager
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.floatOrNull
import kotlinx.serialization.json.jsonPrimitive

/**
 * `assets/models/manifest.json`, generated by tools/fetch_artifacts.py from
 * artifacts.lock.json. The app maps role -> files only through this file.
 */
@Serializable
data class ModelManifest(
    @SerialName("schema_version") val schemaVersion: String,
    @SerialName("lock_sha256") val lockSha256: String,
    val roles: Map<String, Role>,
    val files: List<FileEntry> = emptyList(),
    @SerialName("espeak_data") val espeakData: EspeakData? = null,
) {
    @Serializable
    data class Role(
        @SerialName("artifact_id") val artifactId: String,
        val version: String? = null,
        val license: String = "",
        val sherpa: JsonObject = JsonObject(emptyMap()),
        val files: Map<String, String>,
    ) {
        fun file(key: String): String = files[key] ?: error("Thiếu file '$key' của $artifactId trong manifest")
        fun float(key: String, default: Float): Float = sherpa[key]?.jsonPrimitive?.floatOrNull ?: default
        fun text(key: String): String? = sherpa[key]?.jsonPrimitive?.content
    }

    @Serializable
    data class FileEntry(val path: String, val bytes: Long, val sha256: String)

    @Serializable
    data class EspeakData(
        val dir: String,
        @SerialName("file_count") val fileCount: Int,
        val bytes: Long,
        @SerialName("sha256_tree") val sha256Tree: String,
    )

    fun role(name: String): Role = roles[name] ?: error("Thiếu vai trò '$name' trong models/manifest.json")

    companion object {
        const val ASSET_PATH = "models/manifest.json"
        const val VAD = "vad"
        const val STT_VI = "stt_vi"
        const val STT_EN = "stt_en"
        const val TTS_VI = "tts_vi"
        const val TTS_EN = "tts_en"

        private val json = Json { ignoreUnknownKeys = true }

        fun parse(text: String): ModelManifest = json.decodeFromString(serializer(), text)

        fun load(assets: AssetManager): ModelManifest =
            parse(assets.open(ASSET_PATH).use { it.readBytes().decodeToString() })
    }
}
