package vn.viettechtrans.app.mt

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Parity with Core `build_phase01.norm()` using `core_norm_parity.json`, generated by
 * `tools/build_text_fixtures.py` from Core's own code.
 */
class MtInputNormalizerParityTest {
    private val fixture: JsonObject by lazy {
        val stream = requireNotNull(javaClass.classLoader?.getResourceAsStream("core_norm_parity.json")) {
            "core_norm_parity.json missing: run tools/build_text_fixtures.py"
        }
        Json.parseToJsonElement(stream.use { it.readBytes().decodeToString() }).jsonObject
    }

    @Test
    fun policyIdMatchesFixture() {
        assertEquals(MtInputNormalizer.ID, fixture.getValue("policy_id").jsonPrimitive.content)
    }

    @Test
    fun whitespaceSetMatchesPython() {
        val python = fixture.getValue("python_whitespace_codepoints").jsonArray.map { it.jsonPrimitive.int }
        assertEquals(python.sorted(), PythonWhitespace.CODEPOINTS.sorted())
        for (cp in 0..0xFFFF) {
            assertEquals("U+%04X".format(cp), cp in python, PythonWhitespace.contains(cp.toChar()))
        }
    }

    @Test
    fun deletedSetMatchesFixture() {
        val rule = fixture.getValue("deleted_codepoints_rule").jsonObject
        val deleted = rule.getValue("codepoints").jsonArray.map { it.jsonPrimitive.int }
        assertEquals(deleted.sorted(), MtInputNormalizer.DELETED_CODEPOINTS.sorted())
        for (cp in 0..0xFFFF) {
            assertEquals("U+%04X".format(cp), cp in deleted, MtInputNormalizer.isDeleted(cp.toChar()))
        }
    }

    @Test
    fun everyCaseMatchesCoreNorm() {
        val cases = fixture.getValue("cases").jsonArray
        assertTrue("fixture has no cases", cases.isNotEmpty())
        val failures = mutableListOf<String>()
        for (element in cases) {
            val case = element.jsonObject
            val id = case.getValue("id").jsonPrimitive.content
            val input = case.getValue("input").jsonPrimitive.content
            val expected = case.getValue("expected").jsonPrimitive.content
            case.getValue("core_would_reject").jsonPrimitive.boolean // field must exist
            val actual = MtInputNormalizer.normalize(input)
            if (actual != expected) failures += "$id: expected=${escape(expected)} actual=${escape(actual)}"
        }
        assertTrue("${failures.size}/${cases.size} cases differ:\n" + failures.take(20).joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun keepsCaseAndPunctuation() {
        assertEquals("Git “Push” — OK!", MtInputNormalizer.normalize("  Git “Push” — OK!\n"))
    }

    private fun escape(s: String): String = buildString {
        for (ch in s) if (ch.code < 0x20 || ch.code in 0x7F..0xA0 || ch.code > 0x2000) append("\\u%04X".format(ch.code)) else append(ch)
    }
}
